import {overview,esc,demoPreferences} from './overview.js';
const main=document.querySelector('#main');
// Demo assumes personal images already exist; feedback below is sample copy, not analysis.
const demoPhotoFeedback={summary:'Your expression stands out; lighting and framing could improve.',strengths:['Natural smile','Clear face','Relaxed posture'],weaknesses:['Softer lighting','Cleaner background','Wider framing']};
const defaults={uploadedPhotoCount:1,photoFeedback:demoPhotoFeedback,name:'Mrinal',city:'New York',about:'Looking for a thoughtful partnership and a life built together.',distance:'50 miles',intent:'Marriage',email:true,sms:false,paused:false,familyPlans:'Want 4+ kids',personality:'O: 70 · C: 70 · E: 82 · A: 76 · N: 28',socialLife:'Run Club ATL',preferenceTerms:demoPreferences,faith:'',ageRange:'',familyPreference:'',modules:[{id:'profile',page:'My profile',completed:true},{id:'preferences',page:'Preferences',completed:true}]};
let state;try{state={...defaults,...JSON.parse(localStorage.getItem('keeper-concept')||'{}')}}catch{state={...defaults}}
delete state.ratingIndex;delete state.photoRatings;
state.preferenceTerms=String(state.preferenceTerms||defaults.preferenceTerms).split(',').map(term=>term.trim()).filter(term=>term.toLowerCase()!=='kindle reader').join(', ');
if(['Sociable, Kind, Fair-skinned, Reads books','Sociable, Kind, Fair-skinned, Reads books, Active, Family-minded, Curious'].includes(state.preferenceTerms)) state.preferenceTerms=defaults.preferenceTerms;
state.preferenceTerms=state.preferenceTerms.split(',').map(term=>term.trim()==='Active'?'Health conscious':term.trim()).join(', ');
if(!state.familyPlans)state.familyPlans='Want 4+ kids';
const save=()=>{try{localStorage.setItem('keeper-concept',JSON.stringify(state))}catch{} };
const toast=m=>{const t=document.querySelector('#toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',3000)};
const options=(values,current)=>`<option value="">Choose</option>${values.map(value=>`<option ${current===value?'selected':''}>${esc(value)}</option>`).join('')}`;
const intro=(eyebrow,title,desc)=>`<div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${desc}</p>`;
function render(page='Overview'){
 main.classList.toggle('overview-screen',page==='Overview');
 document.title=page==='Overview'?'Dashboard · Keeper':`${page} · Keeper`;
 document.querySelectorAll('header [data-page]').forEach(b=>{b.classList.toggle('selected',b.dataset.page===page);if(b.dataset.page===page)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});

 if(page==='Overview')main.innerHTML=overview(state);
 if(page==='My profile')main.innerHTML=intro('','My info.','The details your match should know.')+`<form class="card profile-layout" id="profile"><label for="name">First name</label><input id="name" name="name" maxlength="60" required value="${esc(state.name)}"><label for="city">Home city</label><input id="city" name="city" maxlength="100" required value="${esc(state.city)}"><label for="about">What you’re looking for</label><input id="about" name="about" maxlength="300" value="${esc(state.about)}"><label for="familyPlans">Your family plans</label><select name="familyPlans" id="familyPlans">${options(['Want 4+ kids','Want children','Open to children','Do not want children','Not sure yet'],state.familyPlans)}</select><label for="faith">Your faith or beliefs</label><input id="faith" name="faith" maxlength="80" value="${esc(state.faith)}"><label for="personality">Personality (O, C, E, A, N)</label><input name="personality" id="personality" maxlength="100" value="${esc(state.personality)}"><label for="socialLife">Social life</label><input name="socialLife" id="socialLife" maxlength="100" value="${esc(state.socialLife)}"><div class="form-actions"><button class="btn">Save profile</button></div></form>`;
 if(page==='Preferences')main.innerHTML=intro('','Match preferences.','Keep your search aligned with what matters to you.')+`<form class="card profile-layout" id="preferences"><label for="preferenceTerms">Traits that matter to you</label><textarea id="preferenceTerms" name="preferenceTerms" maxlength="400" rows="3">${esc(state.preferenceTerms)}</textarea><p class="field-hint">Separate traits with commas.</p><label for="distance">Search distance</label><select name="distance" id="distance">${['25 miles','50 miles','100 miles','Open to relocating'].map(v=>`<option ${state.distance===v?'selected':''}>${v}</option>`).join('')}</select><label for="intent">Relationship intention</label><select name="intent" id="intent">${['Marriage','A committed relationship'].map(v=>`<option ${state.intent===v?'selected':''}>${v}</option>`).join('')}</select><label for="ageRange">Preferred age range</label><select name="ageRange" id="ageRange">${options(['18–24','25–34','35–44','45–54','55+','No preference'],state.ageRange)}</select><label for="familyPreference">Preferred family plans</label><select name="familyPreference" id="familyPreference">${options(['Wants children','Open to children','Does not want children','No preference'],state.familyPreference)}</select><div class="form-actions"><button class="btn">Save preferences</button></div></form>`;
 if(page==='Photos')main.innerHTML=intro('','Your photos.','Up to three photos: a portrait, a full-length photo, and something you love doing.')+`<section class="card"><span class="badge">Private, local preview</span><div class="photo-grid" id="photos">${[1,2,3].map(i=>`<div class="photo-slot">Photo ${i}</div>`).join('')}</div><label for="upload">Choose photos (JPEG, PNG or WebP; up to 10 MB each)</label><input id="upload" type="file" accept="image/jpeg,image/png,image/webp" multiple><p class="note">Photos are previewed only on this page; they are not uploaded or saved. No attractiveness score is assigned.</p><button class="btn secondary" id="clear-photos">Clear photos</button></section>`;
 if(page==='Settings')main.innerHTML=intro('','Settings.','Manage your search and match updates.')+`<form class="card profile-layout" id="settings"><h3>Match notifications</h3><label><input type="checkbox" name="email" ${state.email?'checked':''}>Email me when there’s a match to review</label><label><input type="checkbox" name="sms" ${state.sms?'checked':''}>Text me when there’s a match to review</label><p class="note">These controls demonstrate the experience. They do not subscribe you to real messages.</p><button class="btn">Save notification preferences</button><hr><h3>Search status</h3><p>${state.paused?'Your search is paused. Your profile and answers are kept.':'Pause your search without losing your profile or answers.'}</p><button type="button" class="btn secondary" id="pause">${state.paused?'Resume search':'Pause my search'}</button></form>`;
 if(page!=='Overview')main.insertAdjacentHTML('afterbegin','<button class="back-dashboard text-button" data-page="Overview">← Dashboard</button>');
 main.querySelectorAll('[data-page]').forEach(b=>b.onclick=e=>{e.preventDefault();render(b.dataset.page);if(b.dataset.field){const field=document.getElementById(b.dataset.field);field?.focus();field?.scrollIntoView({block:'nearest'})}});
 const bind=(id,fn)=>{const el=document.getElementById(id);if(el)el.onclick=fn};
 bind('good-photo',()=>modal('What makes a good photo?','Start with a clear, well-lit portrait where your face is easy to see. Add a full-length image and a photo of something you enjoy. Keep your first image solo, and avoid heavy filters or accessories that hide your face.','<a href="https://www.keeper.ai/photo-testing" target="_blank" rel="noopener">Read Keeper’s photo guide ↗</a>'));
 bind('match-explanation',()=>modal('Your status, explained','No match is ready for review yet. The 4,185 potential fits still need to answer more questions before Keeper can finish evaluating them.','Counts are taken from the supplied screenshot for this concept, not a live Keeper account.'));
 for(const id of ['profile','preferences','settings']){const form=document.getElementById(id);if(form)form.onsubmit=e=>{e.preventDefault();const fd=new FormData(form);if(id==='settings'){state.email=fd.has('email');state.sms=fd.has('sms')}else {for(const [k,v] of fd)state[k]=v}save();toast('Your changes are saved on this device.')}}
 bind('pause',()=>modal(state.paused?'Resume your search?':'Pause your search?',state.paused?'We’ll continue looking from where you left off.':'Your profile will be kept, and you can resume whenever you’re ready.','This changes only the demo.',()=>{state.paused=!state.paused;save();render('Settings');toast(state.paused?'Demo search paused.':'Demo search resumed.')}));
 bind('clear-photos',()=>{state.uploadedPhotoCount=0;delete state.photoFeedback;document.getElementById('upload').value='';document.querySelectorAll('.photo-slot').forEach((e,i)=>e.textContent=`Photo ${i+1}`)});
 const upload=document.getElementById('upload');if(upload)upload.onchange=()=>{const files=[...upload.files];if(files.length>3||files.some(f=>f.size>10*1024*1024||!['image/jpeg','image/png','image/webp'].includes(f.type))){toast('Choose up to 3 JPEG, PNG or WebP images, under 10 MB each.');upload.value='';return}state.uploadedPhotoCount=files.length;delete state.photoFeedback;document.querySelectorAll('.photo-slot').forEach((slot,i)=>{slot.replaceChildren();if(files[i]){const img=new Image();img.alt=`Your selected photo ${i+1}`;img.src=URL.createObjectURL(files[i]);img.onload=()=>URL.revokeObjectURL(img.src);slot.append(img)}else slot.textContent=`Photo ${i+1}`})};
}
function modal(title,body,note,action){const dialog=document.querySelector('#dialog');document.querySelector('#dialog-body').innerHTML=`<div class="eyebrow">Keeper, explained</div><h2 id="dialog-title">${title}</h2><p>${body}</p><p class="note">${note}</p>${action?'<button class="btn" id="confirm">Confirm</button>':''}`;if(action)document.querySelector('#confirm').onclick=()=>{action();dialog.close()};dialog.showModal()}
document.querySelector('.close').onclick=()=>document.querySelector('#dialog').close();document.querySelectorAll('header [data-page]').forEach(b=>b.onclick=()=>render(b.dataset.page));render();
